spring.application.name=token-verification-and-translation-service
server.port=8082

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=token-verification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.uidai.sandbox.common.dto

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWKS Configuration
app.security.jwks-uri=https://example.com/.well-known/jwks.json

